# Generated by Django 5.1.7 on 2025-06-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cell_id", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=200)),
                ("province", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("sector", models.CharField(max_length=100)),
                ("cellule_name", models.CharField(max_length=100)),
            ],
            options={
                "unique_together": {
                    (
                        "cell_id",
                        "country",
                        "province",
                        "district",
                        "sector",
                        "cellule_name",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="farmers.cell",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "national_id",
                    models.CharField(db_index=True, max_length=22, unique=True),
                ),
                ("birth_date", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farmers.village",
                    ),
                ),
            ],
        ),
    ]
