# Generated by Django 5.1.7 on 2025-06-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0003_registrationcode_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
