# Generated by Django 5.1.7 on 2025-06-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_distribution_distributeditem_delete_seeddistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
