# Generated by Django 5.1.7 on 2025-06-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_farmer_is_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmer",
            old_name="registered_at",
            new_name="registreted_at",
        ),
    ]
